import { FileText, Download, CheckCircle, Zap, TrendingDown, BarChart3 } from 'lucide-react';
import { Card } from '../components/Card';
import { useState } from 'react';

const MRVGenerator = () => {
  const [showFullReport, setShowFullReport] = useState(false);

  // Sample generated report data
  const generatedReport = {
    projectName: 'Cement Plant B – Chennai',
    monitoringPeriod: 'January 2024 - March 2024',
    sensorSource: 'IoT Sensor Array (rpi5-facility001)',
    averageCO2: 542.3,
    estimatedReduction: 892,
    dataQuality: 98.5,
    complianceStatus: 'VERIFIED',
    generatedAt: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
  };

  const handleDownloadPDF = () => {
    // Create a simple text report content
    const reportContent = `
MRV VERIFICATION REPORT
Generated by AI Climate Control - SageMaker MRV Engine

PROJECT INFORMATION
Project Name: ${generatedReport.projectName}
Monitoring Period: ${generatedReport.monitoringPeriod}
Sensor Source: ${generatedReport.sensorSource}
Generated Date: ${generatedReport.generatedAt}

KEY METRICS
Average CO₂ Level: ${generatedReport.averageCO2.toFixed(1)} ppm
Estimated CO₂ Reduction: ${generatedReport.estimatedReduction} tCO₂e
Data Quality Score: ${generatedReport.dataQuality.toFixed(1)}%

COMPLIANCE STATUS
Status: ${generatedReport.complianceStatus}
Standard: Gold Standard + Article 6
ML Model: SageMaker Isolation Forest + LSTM

REPORT DETAILS
Report ID: MRV-2024-001-CEMENT-B
Verification Status: VERIFIED

This MRV report was automatically generated using AWS SageMaker ML models. 
All calculations include conservative uncertainty buffers as per international carbon credit standards.
    `;

    // Create blob and download
    const element = document.createElement('a');
    const file = new Blob([reportContent], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = 'MRV-Report-2024-001.txt';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleViewFullReport = () => {
    setShowFullReport(!showFullReport);
  };

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div>
        <h1 className="text-2xl font-bold text-gray-900">MRV Report Generator</h1>
        <p className="text-sm text-gray-600 mt-1">Automated monitoring, reporting, and verification documentation powered by SageMaker</p>
      </div>

      {/* Generated Report Preview */}
      <Card>
        <div className="p-8 bg-gradient-to-br from-blue-50 to-indigo-50">
          {/* Report Header */}
          <div className="flex items-start justify-between mb-8 pb-6 border-b border-blue-200">
            <div>
              <div className="flex items-center space-x-2 mb-2">
                <FileText className="text-blue-600" size={24} />
                <h2 className="text-2xl font-bold text-gray-900">MRV Verification Report</h2>
              </div>
              <p className="text-sm text-gray-600">Generated by AI Climate Control - SageMaker MRV Engine</p>
            </div>
            <div className="text-right">
              <div className="flex items-center space-x-2 px-4 py-2 bg-green-100 rounded-lg mb-2">
                <CheckCircle className="text-green-600" size={20} />
                <span className="text-sm font-semibold text-green-800">{generatedReport.complianceStatus}</span>
              </div>
              <p className="text-xs text-gray-600">Generated: {generatedReport.generatedAt}</p>
            </div>
          </div>

          {/* Report Content */}
          <div className="space-y-6">
            {/* Project Information */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="bg-white rounded-lg p-4 border border-blue-100">
                <p className="text-xs text-gray-600 mb-1">Project Name</p>
                <p className="text-lg font-semibold text-gray-900">{generatedReport.projectName}</p>
              </div>
              <div className="bg-white rounded-lg p-4 border border-blue-100">
                <p className="text-xs text-gray-600 mb-1">Monitoring Period</p>
                <p className="text-lg font-semibold text-gray-900">{generatedReport.monitoringPeriod}</p>
              </div>
            </div>

            {/* Sensor Source */}
            <div className="bg-white rounded-lg p-4 border border-blue-100">
              <p className="text-xs text-gray-600 mb-1">Sensor Source</p>
              <p className="text-lg font-semibold text-gray-900">{generatedReport.sensorSource}</p>
            </div>

            {/* Key Metrics */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="bg-white rounded-lg p-4 border border-blue-100">
                <div className="flex items-center space-x-2 mb-2">
                  <Zap className="text-orange-500" size={18} />
                  <p className="text-xs text-gray-600">Average CO₂ Level</p>
                </div>
                <p className="text-2xl font-bold text-gray-900">{generatedReport.averageCO2.toFixed(1)}</p>
                <p className="text-xs text-gray-500 mt-1">ppm</p>
              </div>

              <div className="bg-white rounded-lg p-4 border border-blue-100">
                <div className="flex items-center space-x-2 mb-2">
                  <TrendingDown className="text-green-600" size={18} />
                  <p className="text-xs text-gray-600">Estimated CO₂ Reduction</p>
                </div>
                <p className="text-2xl font-bold text-gray-900">{generatedReport.estimatedReduction}</p>
                <p className="text-xs text-gray-500 mt-1">tCO₂e</p>
              </div>

              <div className="bg-white rounded-lg p-4 border border-blue-100">
                <div className="flex items-center space-x-2 mb-2">
                  <BarChart3 className="text-blue-600" size={18} />
                  <p className="text-xs text-gray-600">Data Quality Score</p>
                </div>
                <p className="text-2xl font-bold text-gray-900">{generatedReport.dataQuality.toFixed(1)}%</p>
                <p className="text-xs text-gray-500 mt-1">Verified</p>
              </div>
            </div>

            {/* Compliance Status */}
            <div className="bg-green-50 border border-green-200 rounded-lg p-4">
              <div className="flex items-start space-x-3">
                <CheckCircle className="text-green-600 flex-shrink-0 mt-0.5" size={20} />
                <div>
                  <h4 className="text-sm font-semibold text-green-900 mb-1">Compliance Status: VERIFIED</h4>
                  <p className="text-sm text-green-800">
                    This report meets Gold Standard and Article 6 compliance requirements. All data has been validated through the SageMaker anomaly detection pipeline with 98.5% data quality assurance.
                  </p>
                </div>
              </div>
            </div>

            {/* Report Footer */}
            <div className="pt-4 border-t border-blue-200 text-xs text-gray-600">
              <p>This MRV report was automatically generated using AWS SageMaker ML models. All calculations include conservative uncertainty buffers as per international carbon credit standards.</p>
            </div>
          </div>
        </div>
      </Card>

      {/* Action Buttons */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <button 
          onClick={handleDownloadPDF}
          className="flex items-center justify-center space-x-2 px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium"
        >
          <Download size={20} />
          <span>Download PDF Report</span>
        </button>
        <button 
          onClick={handleViewFullReport}
          className="flex items-center justify-center space-x-2 px-6 py-3 bg-gray-200 text-gray-900 rounded-lg hover:bg-gray-300 transition-colors font-medium"
        >
          <FileText size={20} />
          <span>{showFullReport ? 'Hide Full Report' : 'View Full Report'}</span>
        </button>
      </div>

      {/* Full Report View */}
      {showFullReport && (
        <Card>
          <div className="p-8 bg-white">
            <h3 className="text-xl font-bold text-gray-900 mb-6">Complete MRV Report</h3>
            <div className="space-y-4 text-sm text-gray-700 whitespace-pre-wrap font-mono bg-gray-50 p-6 rounded-lg border border-gray-200">
              {`MRV VERIFICATION REPORT
Generated by AI Climate Control - SageMaker MRV Engine

PROJECT INFORMATION
Project Name: ${generatedReport.projectName}
Monitoring Period: ${generatedReport.monitoringPeriod}
Sensor Source: ${generatedReport.sensorSource}
Generated Date: ${generatedReport.generatedAt}

KEY METRICS
Average CO₂ Level: ${generatedReport.averageCO2.toFixed(1)} ppm
Estimated CO₂ Reduction: ${generatedReport.estimatedReduction} tCO₂e
Data Quality Score: ${generatedReport.dataQuality.toFixed(1)}%

COMPLIANCE STATUS
Status: ${generatedReport.complianceStatus}
Standard: Gold Standard + Article 6
ML Model: SageMaker Isolation Forest + LSTM

REPORT DETAILS
Report ID: MRV-2024-001-CEMENT-B
Verification Status: VERIFIED

This MRV report was automatically generated using AWS SageMaker ML models. 
All calculations include conservative uncertainty buffers as per international carbon credit standards.`}
            </div>
          </div>
        </Card>
      )}

      {/* Report Details */}
      <Card>
        <div className="p-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">Report Details</h3>
          <div className="space-y-3">
            <div className="flex justify-between items-center py-2 border-b border-gray-200">
              <span className="text-sm text-gray-600">Report ID</span>
              <span className="text-sm font-medium text-gray-900">MRV-2024-001-CEMENT-B</span>
            </div>
            <div className="flex justify-between items-center py-2 border-b border-gray-200">
              <span className="text-sm text-gray-600">Standard</span>
              <span className="text-sm font-medium text-gray-900">Gold Standard + Article 6</span>
            </div>
            <div className="flex justify-between items-center py-2 border-b border-gray-200">
              <span className="text-sm text-gray-600">ML Model</span>
              <span className="text-sm font-medium text-gray-900">SageMaker Isolation Forest + LSTM</span>
            </div>
            <div className="flex justify-between items-center py-2">
              <span className="text-sm text-gray-600">Verification Status</span>
              <span className="px-3 py-1 bg-green-100 text-green-700 text-sm font-medium rounded-full">VERIFIED</span>
            </div>
          </div>
        </div>
      </Card>
    </div>
  );
};

export default MRVGenerator;
